spring:
  config:
    activate:
      on-profile: local
jwt:
  secret: Bj5eT2ZMn3CfXk9Ui6GvV4YqQ2Dc9AtBm7FeR8HtK9OvZ6Px
  expiration: 900000 # 15 minutes
  refresh-expiration: 604800000 # 7 days
---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  secret: ${{JWT_SECRET}}
  expiration: 900000 # 15 minutes
  refresh-expiration: 604800000 # 7 days
