server:
  port: 8080
  shutdown: graceful
spring:
  profiles:
    active: local
    include:
      - persistence
      - redis
      - application
  jackson:
    property-naming-strategy: SNAKE_CASE
  transaction:
    default-timeout: 4
---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      file: ./user/user-api/rest/docker-compose.yml
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: false
springdoc:
  swagger-ui:
    enabled: false
