server:
  port: 8080
  shutdown: graceful
spring:
  profiles:
    active: local
    include:
      - kafka
      - websocket

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    topics:
      - post-create

---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      file: ./post/post-api/websocket/docker-compose.yaml
---
spring:
  config:
    activate:
      on-profile: dev
