server:
  port: 8081
  shutdown: graceful
spring:
  profiles:
    active: local
    include:
      - kafka
      - application
---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: false
#      file: ./post/post-api/rest/docker-compose.yaml
---
spring:
  config:
    activate:
      on-profile: dev
