spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      file: ./post/post-api/rest/docker-compose.yaml
---
spring:
  config:
    activate:
      on-profile: dev
