server:
  port: 8080
  shutdown: graceful
spring:
  profiles:
    active: local
    include:
      - kafka
      - application
---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: true
      file: ./post/post-api/rest/docker-compose.yaml
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: false
springdoc:
  swagger-ui:
    enabled: false
