spring:
  config:
    activate:
      on-profile: local
kafka:
  producer:
    bootstrap-servers: localhost:9092
    post-create-topic: post-create
---
spring:
  config:
    activate:
      on-profile: dev
