name: Gradle Test

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/user_service_test.yaml'
      - 'user-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: |
          cd user-service
          chmod +x gradlew

      - name: Run Tests with Gradle
        run: |
          cd user-service
          ./gradlew test
